# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNgo6sDEP__62J6ny9Mg2Twidh1GBep_
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# Load model
model = tf.keras.models.load_model("cnn_cifar10.keras")

# Nama kelas CIFAR-10
class_names = [
    "Airplane", "Automobile", "Bird", "Cat", "Deer",
    "Dog", "Frog", "Horse", "Ship", "Truck"
]

st.title("CNN CIFAR-10 Image Classifier")

uploaded_file = st.file_uploader(
    "Upload sebuah gambar",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file)

    st.image(image, caption="Gambar yang diupload", use_container_width=True)

    image = image.resize((32, 32))
    image = np.array(image)

    # Pastikan gambar RGB
    if image.shape[-1] == 4:
        image = image[:, :, :3]

    image = image.astype("float32") / 255.0
    image = np.expand_dims(image, axis=0)

    prediction = model.predict(image)

    predicted_class = class_names[np.argmax(prediction)]

    confidence = np.max(prediction) * 100

    st.success(f"Prediksi : {predicted_class}")
    st.write(f"Confidence : {confidence:.2f}%")